### Lecture 2

In [1]:
import numpy as np

In [2]:
arr1 = np.arange(12)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
arr1.shape

(12,)

In [4]:
arr1.size

12

In [5]:
arr1.dtype

dtype('int32')

In [6]:
def info_array(a):                     # creating function for shape,size,type & dim
    print("Dimenshion - ", a.ndim)
    print("Shape -" ,a.shape)
    print("Number of elements -" ,a.size)
    print("Datatype -" ,a.dtype)

In [7]:
info_array(arr1)

Dimenshion -  1
Shape - (12,)
Number of elements - 12
Datatype - int32


### Linspace

In [8]:
arr2 = np.linspace(1,2,34)
arr2

array([1.        , 1.03030303, 1.06060606, 1.09090909, 1.12121212,
       1.15151515, 1.18181818, 1.21212121, 1.24242424, 1.27272727,
       1.3030303 , 1.33333333, 1.36363636, 1.39393939, 1.42424242,
       1.45454545, 1.48484848, 1.51515152, 1.54545455, 1.57575758,
       1.60606061, 1.63636364, 1.66666667, 1.6969697 , 1.72727273,
       1.75757576, 1.78787879, 1.81818182, 1.84848485, 1.87878788,
       1.90909091, 1.93939394, 1.96969697, 2.        ])

In [9]:
arr3 = np.linspace(10,45,6)
arr3

array([10., 17., 24., 31., 38., 45.])

In [10]:
arr4 = np.linspace(1,9,3)
arr4

array([1., 5., 9.])

In [11]:
arr5 = np.linspace(1,5,125)
arr5

array([1.        , 1.03225806, 1.06451613, 1.09677419, 1.12903226,
       1.16129032, 1.19354839, 1.22580645, 1.25806452, 1.29032258,
       1.32258065, 1.35483871, 1.38709677, 1.41935484, 1.4516129 ,
       1.48387097, 1.51612903, 1.5483871 , 1.58064516, 1.61290323,
       1.64516129, 1.67741935, 1.70967742, 1.74193548, 1.77419355,
       1.80645161, 1.83870968, 1.87096774, 1.90322581, 1.93548387,
       1.96774194, 2.        , 2.03225806, 2.06451613, 2.09677419,
       2.12903226, 2.16129032, 2.19354839, 2.22580645, 2.25806452,
       2.29032258, 2.32258065, 2.35483871, 2.38709677, 2.41935484,
       2.4516129 , 2.48387097, 2.51612903, 2.5483871 , 2.58064516,
       2.61290323, 2.64516129, 2.67741935, 2.70967742, 2.74193548,
       2.77419355, 2.80645161, 2.83870968, 2.87096774, 2.90322581,
       2.93548387, 2.96774194, 3.        , 3.03225806, 3.06451613,
       3.09677419, 3.12903226, 3.16129032, 3.19354839, 3.22580645,
       3.25806452, 3.29032258, 3.32258065, 3.35483871, 3.38709

In [12]:
info_array(arr5)

Dimenshion -  1
Shape - (125,)
Number of elements - 125
Datatype - float64


## Re-Shape

In [13]:
arr6 = np.linspace(1,24,24, dtype="int")
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [14]:
arr6.shape

(24,)

In [15]:
arr6.reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

* Reshape above array with following shapes - (12,2), (2,12), (8,3), (3,8), (3,4,2)

In [16]:
arr6.reshape(3,4,2)  # creates 3 layers with 4 rows and 2 columns

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [17]:
arr6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [18]:
arr6 = arr6.reshape(6,4)
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [19]:
arr6.reshape(24)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## Ravel

In [20]:
arr6.ravel("C") # C Programming

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [21]:
arr6.ravel("F") # FORTRON 77 Programming(joins the element according to column)

array([ 1,  5,  9, 13, 17, 21,  2,  6, 10, 14, 18, 22,  3,  7, 11, 15, 19,
       23,  4,  8, 12, 16, 20, 24])

## Resize

In [22]:
arr6.resize(8,3)

In [23]:
arr6

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [24]:
arr6.resize(3,8)
arr6

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [25]:
np.resize(arr6, (7,5))  # adds elements in the end to complete 7 rows and 5 columns

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24,  1],
       [ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11]])

In [26]:
np.resize(arr6, (3,4))  # prints only elements till 3rd row and 4 columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
arr7 = np.arange(4,16).reshape(3,4)
arr7

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
np.resize(arr7, (5,4))  # adds two more rows starting from the first element to complelte 5 rows

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
arr8 = np.arange(1,7).reshape(2,3)
arr8

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr9 = np.arange(7,13).reshape(2,3)
arr9

array([[ 7,  8,  9],
       [10, 11, 12]])

### Concatenate

In [31]:
np.concatenate([arr8, arr9])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [32]:
np.concatenate([arr8, arr9], axis=1)  ### concatenate column wise

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [33]:
np.concatenate([arr8, arr9], axis=0)   ### concatenate row wise

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
arr10 = np.arange(13,19).reshape(2,3)
arr10

array([[13, 14, 15],
       [16, 17, 18]])

In [35]:
np.concatenate([arr8, arr10], axis=0)  ## not possible bz row and column size is not same

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [13, 14, 15],
       [16, 17, 18]])

## H-stack

In [36]:
arr8

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
arr9

array([[ 7,  8,  9],
       [10, 11, 12]])

In [38]:
np.hstack([arr8, arr9])  # horizontal stack joins columns

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [39]:
np.vstack([arr8, arr9])  # vertical stack joins rows

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Repeat 

In [40]:
arr11 = np.arange(3)
arr11

array([0, 1, 2])

In [41]:
arr11.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [42]:
arr11.repeat(11)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [43]:
arr11.repeat([3,15,11])  # (1st elements repeats -3 times, 2nd - 15 times, 3rd times- 11 times)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2])

## Identity Matrix

In [44]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [45]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [46]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [47]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.eye(3,7, 4) # (number of rows,columns and 0...4 index number)

array([[0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [49]:
np.ones((3,4)) # Unit Matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
np.zeros((3,6)) # Null Matrix

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## Split

In [51]:
arr12 = np.linspace(1,100, 100, dtype = "int").reshape(10,10)
arr12

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [52]:
np.split(arr12, [3, 6])   

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]),
 array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]]),
 array([[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])]

In [53]:
np.split(arr12, [3,6])

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]),
 array([[31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
        [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]]),
 array([[ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])]

In [54]:
np.split(arr12, [3])

[array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]]),
 array([[ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
        [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
        [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
        [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
        [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
        [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
        [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])]

In [64]:
np.split(arr12, [2,4,6,8], axis = 1)

[array([[ 1,  2],
        [11, 12],
        [21, 22],
        [31, 32],
        [41, 42],
        [51, 52],
        [61, 62],
        [71, 72],
        [81, 82],
        [91, 92]]),
 array([[ 3,  4],
        [13, 14],
        [23, 24],
        [33, 34],
        [43, 44],
        [53, 54],
        [63, 64],
        [73, 74],
        [83, 84],
        [93, 94]]),
 array([[ 5,  6],
        [15, 16],
        [25, 26],
        [35, 36],
        [45, 46],
        [55, 56],
        [65, 66],
        [75, 76],
        [85, 86],
        [95, 96]]),
 array([[ 7,  8],
        [17, 18],
        [27, 28],
        [37, 38],
        [47, 48],
        [57, 58],
        [67, 68],
        [77, 78],
        [87, 88],
        [97, 98]]),
 array([[  9,  10],
        [ 19,  20],
        [ 29,  30],
        [ 39,  40],
        [ 49,  50],
        [ 59,  60],
        [ 69,  70],
        [ 79,  80],
        [ 89,  90],
        [ 99, 100]])]

In [56]:
sp1,sp2,sp3 = np.split(arr12, [4,7], axis = 1)

In [57]:
sp1

array([[ 1,  2,  3,  4],
       [11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44],
       [51, 52, 53, 54],
       [61, 62, 63, 64],
       [71, 72, 73, 74],
       [81, 82, 83, 84],
       [91, 92, 93, 94]])

In [58]:
sp2

array([[ 5,  6,  7],
       [15, 16, 17],
       [25, 26, 27],
       [35, 36, 37],
       [45, 46, 47],
       [55, 56, 57],
       [65, 66, 67],
       [75, 76, 77],
       [85, 86, 87],
       [95, 96, 97]])

In [59]:
sp3

array([[  8,   9,  10],
       [ 18,  19,  20],
       [ 28,  29,  30],
       [ 38,  39,  40],
       [ 48,  49,  50],
       [ 58,  59,  60],
       [ 68,  69,  70],
       [ 78,  79,  80],
       [ 88,  89,  90],
       [ 98,  99, 100]])